config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'countries#index'
  resources :countries, only: [:index]
  resources :cities, only: [:index]
  resource :dijkstra, only: [:show]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :countries, only: [:index, :show] do
        resources :cities, only: [:index]
      end
      resources :cities, only: [:index, :show]
      resources :dijkstras, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :starting_roads, class_name: 'Road', foreign_key: 'city_start_id'
  has_many :ending_roads, class_name: 'Road', foreign_key: 'city_end_id'
  validates :name, presence: true

  geocoded_by :name
  after_validation :geocode, if: ->(city) { city.latitude.nil? }

  def roads
    starting_roads + ending_roads
  end

  def connected_cities
    City.where(id: roads.pluck(:city_start_id, :city_end_id).flatten.uniq - [id])
  end

  def connected_roads
    roads.each_with_object([]) do |road, object|
      object << [self == road.city_start ? road.city_end.name : road.city_start.name, road.distance]
    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities, dependent: :destroy
  has_many :roads, dependent: :destroy
  validates :name, presence: true
end

app/models/road.rb
class Road < ApplicationRecord
  belongs_to :city_start, class_name: 'City'
  belongs_to :city_end, class_name: 'City'
  belongs_to :country

  def name
    "#{city_start.name} - #{city_end.name}"
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  include ActionController::HttpAuthentication::Basic::ControllerMethods

  http_basic_authenticate_with name: ENV['BASIC_USER'], password: ENV['BASIC_PASSWORD']
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < Api::V1::BaseController
  def index
    @cities = params[:country_id].nil? ? City.all : City.where("country_id = #{params[:country_id]}")
    options_api = {}
    options_api[:meta] = { total: @cities.count }
    render_json(@cities, options_api)
  end

  def show
    @city = City.find(params[:id])
    render_json(@city)
  end

  private 

  def render_json(cities, options_api = {})
    json_api = CitySerializer.new(cities, options_api).serializable_hash.to_json
    render json: json_api
  end
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < Api::V1::BaseController
  def index
    @countries = Country.all
    options_api = {}
    options_api[:meta] = { total: @countries.count }
    render_json(@countries, options_api)
  end

  def show 
    @country = Country.find(params[:id])
    render_json(@country)
  end

  private 

  def render_json(countries, options_api={})
    json_api = CountrySerializer.new(countries, options_api).serializable_hash.to_json
    render json: json_api
  end
end

app/controllers/api/v1/dijkstras_controller.rb
class Api::V1::DijkstrasController < Api::V1::BaseController
  before_action :set_city, only: [:create]

  def create
    if @city_start.country == @city_end.country
      path, distance = Dijkstras::Create.execute(@city_start, @city_end)
      path = build_journey(path)
      json_api = DijkstraSerializer.new(@city_start, { params:
      {
        path: path,
        distance: distance,
        city_start_id: @city_start.id,
        city_end_id: @city_end.id
      } }).serializable_hash.to_json
      render json: json_api
    else
      render json: { error: 'Cities must be from the same country' }
    end
  end

  private

  def build_journey(path)
    path.each_with_object([]) do |city_name, array|
      city = City.find_by(name: city_name)
      array << { city_name: city_name, longitude: city.longitude, latitude: city.latitude, id: city.id }
    end
  end

  def set_city
    @city_start = City.find(params.dig('data', 'attributes', 'city_start_id') || params['city_start_id'])
    @city_end = City.find(params.dig('data', 'attributes', 'city_end_id') || params['city_end_id'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.where('country_id = ?', params[:country_id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end
end

app/controllers/dijkstras_controller.rb
class DijkstrasController < ApplicationController
  before_action :set_city, only: [:show]

  def show
    if @city_start.country == @city_end.country
      belgium_mapping = DijkstraService.new_graph
      @path, @distance = DijkstraService.path_distance(@city_start.name, @city_end.name, belgium_mapping)
    else
      render :error
    end
  end

  private

  def set_city
    @city_start = City.find(params[:city_start_id])
    @city_end = City.find(params[:city_end_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/cities/index.html.erb
<div class="container">

  <%= form_with url: dijkstra_path, method: :get, local:true do |form| %>
    <%= form.label :city_start, "From:" %>
    <%= form.select :city_start_id, @cities.map{ |city| [city.name, city.id] }, include_blank: true %>
    <%= form.label :city_end, "To:" %>
    <%= form.select :city_end_id, @cities.map{ |city| [city.name, city.id] }, include_blank: true %>
    <%= form.submit "Confirm" %>
  <% end %>



</div>

app/views/countries/index.html.erb
<div class="container">

  <%= form_with url: cities_path, method: :get, local:true do |form| %>
    <%= form.select :country_id, @countries.map { |country| [country.name, country.id] },  include_blank: true %>
    <%= form.submit "Confirm" %>
  <% end %>

</div>

app/views/dijkstras/error.html.erb
<h2> Oupsie </h2>
<p> The cities must be in the same country</p>
<%= link_to 'Back', :back %>

app/views/dijkstras/shortest_path.html.erb
<div class="container">
  <p>Your journey : <%= @path.join(", ") %> </p>
  <p>Your distance : <%= @distance %> km </p>
</div>

app/views/dijkstras/show.html.erb
<div class="container">
  <p>Your journey : <%= @path.join(", ") %> </p>
  <p>Your distance : <%= @distance %> km </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dijkstra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

  <%= form_with url: "/direction", method: :get, local:true do |form| %>
    <%= form.select :country, Country.all.map(&:name), include_blank: true %>
    <%= form.submit "Confirm" %>
  <% end %>

</div>